AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./deploy/api.yaml
      StageName: prod
      Variables:
        LambdaFunctionName: !Ref ResizeFunction

  FileBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        RoutingRules:
          - RedirectRule:
              HttpRedirectCode: 307
              HostName: !Sub ${Api}.execute-api.${AWS::Region}.amazonaws.com
              Protocol: https
              ReplaceKeyPrefixWith: prod?key=
            RoutingRuleCondition:
              HttpErrorCodeReturnedEquals: 404

  ResizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/function.zip
      Handler: index.handler
      Runtime: nodejs6.10
      MemorySize: 1536
      Timeout: 60
      Environment:
        Variables:
          BUCKET: !Ref FileBucket
          URL: !GetAtt FileBucket.WebsiteURL
      Policies:
          Statement:
            - Resource: !Sub arn:aws:s3:::${FileBucket}/*
              Effect: Allow
              Action:
                - s3:PutObject

  ResizeFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ResizeFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*

  FileBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FileBucket
      PolicyDocument:
        Statement:
          - Action: 
            - s3:GetObject
            - s3:GetObjectVersion
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:DeleteObject
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::067246364203:user/developer
            Resource: !Sub arn:aws:s3:::${FileBucket}/*
          - Action: s3:GetObject
            Effect: Allow
            Principal: "*"
            Resource: !Sub arn:aws:s3:::${FileBucket}/*

Outputs:
  BucketWebsiteUrl:
    Value: !GetAtt FileBucket.WebsiteURL
  Bucket:
    Value: !Ref FileBucket
